### ISSUE TITLE
Help me improve the game! - Suggestions and your own features.

### ISSUE THREAD

**Issue by Bavuett** [DevLBD/Breakout-Java#1]
## Looking for a new project to work on?

If you wish to suggest something, or - if you'd like - even make something yourself, you are absolutely free to do so!

**Comment by pradhumna22** [comment]
I would like to contribute on this project.

**Comment by Bavuett** [comment]
Sure! If you have something to improve, go ahead!

Some comments are in Italian. I will correct this when I have time, but you can use Google Translate as a workaround at the moment.
